Name:           ros-hydro-rosnode-rtc
Version:        1.2.3
Release:        0%{?dist}
Summary:        ROS rosnode_rtc package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rosnode_rtc
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-openrtm-tools
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-openrtm-tools
BuildRequires:  ros-hydro-roscpp-tutorials
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-rostopic

%description
This package gives transparency between RTM and ROS. rtmros-data-bridge.py is a
RT-Component for dataport/topic. This automatically convert ROS/topic into
RTM/dataport.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Sep 03 2014 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.2.3-0
- Autogenerated by Bloom

* Sun Aug 31 2014 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.2.2-0
- Autogenerated by Bloom

