Name:           ros-kinetic-rtmros-common
Version:        1.4.2
Release:        0%{?dist}
Summary:        ROS rtmros_common package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rtmros_common
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-hrpsys-ros-bridge
Requires:       ros-kinetic-hrpsys-tools
Requires:       ros-kinetic-openrtm-ros-bridge
Requires:       ros-kinetic-openrtm-tools
Requires:       ros-kinetic-rosnode-rtc
Requires:       ros-kinetic-rtmbuild
BuildRequires:  ros-kinetic-catkin

%description
A package suite that provides all the capabilities for the ROS users to connect
to the robots that run on RT Middleware or RTM-based controllers.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Dec 22 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.4.2-0
- Autogenerated by Bloom

* Wed Aug 09 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.4.0-1
- Autogenerated by Bloom

* Wed Aug 09 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.4.0-0
- Autogenerated by Bloom

