Name:           ros-jade-rosnode-rtc
Version:        1.3.2
Release:        0%{?dist}
Summary:        ROS rosnode_rtc package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rosnode_rtc
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-openrtm-tools
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-openrtm-tools
BuildRequires:  ros-jade-roscpp-tutorials
BuildRequires:  ros-jade-rospy
BuildRequires:  ros-jade-rostopic

%description
This package gives transparency between RTM and ROS. rtmros-data-bridge.py is a
RT-Component for dataport/topic. This automatically convert ROS/topic into
RTM/dataport.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Apr 26 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.3.2-0
- Autogenerated by Bloom

